import './globals.css';

export const metadata = {
    title: 'Stoxie | Smarter Investing',
    description: 'Generated by create next app',
};

import { SmoothScroll } from '@/components/common/smooth-scroll';
import Header from '@/components/layout/header';
import { ThemeProvider } from '@/components/theme-provider';

export default function RootLayout({ children }) {
    return (
        <>
            <html lang='en' suppressHydrationWarning>
                <head />
                <body suppressHydrationWarning className={`antialiased`}>
                    <SmoothScroll />
                    <ThemeProvider
                        attribute='class'
                        defaultTheme='system'
                        enableSystem
                        disableTransitionOnChange>
                        <div className='overflow-hidden'>
                            <Header />
                            {children}
                        </div>
                    </ThemeProvider>
                </body>
            </html>
        </>
    );
}

